/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AboutCard: typeof import('./src/components/AboutCard.vue')['default']
    EmptyStates: typeof import('./src/components/EmptyStates.vue')['default']
    FloatingactionButtons: typeof import('./src/components/FloatingactionButtons.vue')['default']
    NewsdataCard: typeof import('./src/components/NewsdataCard.vue')['default']
    ProductCard: typeof import('./src/components/ProductCard.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SwiperCarousel: typeof import('./src/components/SwiperCarousel.vue')['default']
  }
}
